# Generated by Django 6.0.5 on 2026-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_image_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
