# Generated by Django 6.0.5 on 2026-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='created_at',
            new_name='purchased_at',
        ),
    ]
