# Generated by Django 6.0.5 on 2026-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('FPS', 'FPS'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('MOBA', 'MOBA'), ('Sports', 'Sports'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy')], default='Action', max_length=50),
        ),
    ]
